[project]
name = "augmentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "notebook>=7.4.0",
    "tensorflow-cpu>=2.18.0",
]
