[project]
name = "augmentation"
version = "0.0.1"
description = "Augmenting facial datasets with TensorFlow machine learning models!"
readme = "readme.txt"
requires-python = "==3.11.12"
dependencies = [
    "matplotlib",
    "notebook",
    "tensorflow-cpu==2.15.0",
    "scikit-learn",
]
